#!/bin/sh
# . "$(dirname "$0")/_/husky.sh"
# . "$(dirname "$0")/common.sh"

# [ -n "$CI" ] && exit 0

# Format and submit code according to lintstagedrc.js configuration
# pnpm run lint:lint-staged
# lint-staged只能用esm 而 electron不能用esm